import { pageHead } from "./styles";
import { esc } from "./html";

/** Full marketing site chrome: nav with links + footer. */
export function marketingShell(title: string, body: string, opts?: { activeNav?: string }): string {
  const active = opts?.activeNav ?? "";
    const navLink = (href: string, label: string, key: string) =>
        `<a href="${href}" class="${key === active ? "active" : ""}">${label}</a>`;

          return `<!doctype html>
          <html lang="en">
          <head>${pageHead(title)}</head>
          <body>
            <div class="nav">
                <div class="wordmark">MOTO ID</div>
                    <div class="links">
                          ${navLink("/#how-it-works", "HOW IT WORKS", "how")}
                                ${navLink("/#the-mark", "THE MARK", "mark")}
                                      ${navLink("/verify", "VERIFY A VEHICLE", "verify")}
                                            ${navLink("/pricing", "PRICING", "pricing")}
                                                </div>
                                                    <div class="right">
                                                          <a href="/login">SIGN IN</a>
                                                                <a href="/signup" class="text-link">Enquire</a>
                                                                    </div>
                                                                      </div>
                                                                        ${body}
                                                                          <div class="footer">
                                                                              <div class="cols" style="justify-content:space-between">
                                                                                    <div>
                                                                                            <div style="font-weight:600;font-size:11px;letter-spacing:0.18em;margin-bottom:10px">MOTO ID</div>
                                                                                                    <div class="subtle" style="font-size:12.5px;max-width:220px">Digital provenance for exceptional cars and motorcycles.</div>
                                                                                                          </div>
                                                                                                                <div class="cols">
                                                                                                                        <div>
                                                                                                                                  <div class="col-title">STUDIO</div>
                                                                                                                                            <div class="col-links"><div>How it works</div><div>The Mark</div><div>Pricing</div></div>
                                                                                                                                                    </div>
                                                                                                                                                            <div>
                                                                                                                                                                      <div class="col-title">COMPANY</div>
                                                                                                                                                                                <div class="col-links"><div>About</div><div>Contact</div></div>
                                                                                                                                                                                        </div>
                                                                                                                                                                                                <div>
                                                                                                                                                                                                          <div class="col-title">LEGAL</div>
                                                                                                                                                                                                                    <div class="col-links"><div>Privacy</div><div>Terms</div></div>
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                          <div class="container subtle" style="font-size:10.5px;padding-bottom:36px">&copy; ${new Date().getFullYear()} Moto ID. All rights reserved.</div>
                                                                                                                                                                                                                                          </body>
                                                                                                                                                                                                                                          </html>`;
                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                          /** Minimal chrome for auth-style flows (sign up, log in, register a vehicle): logo only, centered card. */
                                                                                                                                                                                                                                          export function authShell(title: string, body: string): string {
                                                                                                                                                                                                                                            return `<!doctype html>
                                                                                                                                                                                                                                            <html lang="en">
                                                                                                                                                                                                                                            <head>${pageHead(title)}</head>
                                                                                                                                                                                                                                            <body style="min-height:100vh;display:flex;flex-direction:column">
                                                                                                                                                                                                                                              <div style="padding:26px 56px;border-bottom:1px solid var(--hairline)">
                                                                                                                                                                                                                                                  <a href="/" class="wordmark">MOTO ID</a>
                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                      <div style="flex:1 1 0;display:flex;align-items:center;justify-content:center;padding:60px 24px">
                                                                                                                                                                                                                                                          ${body}
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                            </html>`;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            /** Signed-in product chrome: topbar with breadcrumb + account avatar. */
                                                                                                                                                                                                                                                            export function appShell(
                                                                                                                                                                                                                                                              title: string,
                                                                                                                                                                                                                                                                breadcrumb: string,
                                                                                                                                                                                                                                                                  body: string,
                                                                                                                                                                                                                                                                    user: { name: string }
                                                                                                                                                                                                                                                                    ): string {
                                                                                                                                                                                                                                                                      const initials = esc(
                                                                                                                                                                                                                                                                          user.name
                                                                                                                                                                                                                                                                                .split(/\s+/)
                                                                                                                                                                                                                                                                                      .map((p) => p[0])
                                                                                                                                                                                                                                                                                            .slice(0, 2)
                                                                                                                                                                                                                                                                                                  .join("")
                                                                                                                                                                                                                                                                                                        .toUpperCase()
                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                            return `<!doctype html>
                                                                                                                                                                                                                                                                                                            <html lang="en">
                                                                                                                                                                                                                                                                                                            <head>${pageHead(title)}</head>
                                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                                  <div style="display:flex;align-items:center;justify-content:space-between;padding:20px 32px;border-bottom:1px solid var(--hairline)">
                                                                                                                                                                                                                                                                                                                  <div style="display:flex;align-items:center;gap:16px">
                                                                                                                                                                                                                                                                                                                         <a href="/dashboard" class="wordmark">MOTO ID</a>
                                                                                                                                                                                                                                                                                                                              <div style="width:1px;height:14px;background:var(--hairline)"></div>
                                                                                                                                                                                                                                                                                                                                    <div class="subtle breadcrumb" style="font-size:12.5px">${breadcrumb}</div>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                             <div style="display:flex;align-items:center;gap:16px">
                                                                                                                                                                                                                                                                                                                                                  <a href="/settings" style="width:32px;height:32px;border-radius:50%;border:1px solid var(--hairline);display:flex;align-items:center;justify-content:center;font-family:var(--font-mono);font-size:11px;color:var(--ink-muted)">${initials}</a>
                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                          <div style="padding:36px 32px;max-width:1200px;margin:0 auto">
                                                                                                                                                                                                                                                                                                                                                              ${body}
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                </html>`;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                
